[versions]
frida = "17.7.3"
guava = "33.2.1-jre"
kotlinx-coroutines = "1.9.0"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.0.0" }
android-library = { id = "com.android.library", version = "8.7.0" }
